# Nominal values for backpack v1 - 90 Deg rotating lidar, spaceship
# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0.1, 0.707,0,0.707,0]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.0025
VELODYNE_LASER_TIME_OFFSET: 0.0025
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [0,0,-1]
