# Nominal values for the backpack as modelled for sim
# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [0.006,0.005,0.031, 1,0,0,0]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0.009,0.000,0.099, 0.653,-0.271,0.271,-0.653]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.0
VELODYNE_LASER_TIME_OFFSET: 0.0
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [1,0,0]
