import numpy as np
import cv2
from lxml import etree
from utils import img_helpers

"""
Class to represent any terrains loaded into mujoco. Terrains are generated by
loading numpy arrays as PNG images into either Mesh or Hfield objects (defined in xml)

NOTE: Both the original array AND the PNG format are stored
"""
class Terrain():
    def __init__(self, terr_arr, path, name):
        self.name = name
        self.img_name = self.name + ".png"
        self.img_path = path + self.img_name

        # terrain array (numpy array)
        self.terr_arr = terr_arr         
        # terrain image (PNG)
        self.terr_img = self.load_terr_img() 
        # image dimensions (pixels)
        self.image_dim = self.terr_arr.shape

    def load_terr_img(self):
        """ 
        Saves the terrain image to its path and returns it
        """ 
        cv2.imwrite(self.img_path, self.terr_arr)
        img = cv2.imread(self.img_path)
        return img
    
    def compute_sub_section(self, i, j, n, m):
        """
        Given an (i, j) index in the terrain array, compute the n x m subsection around (i, j)

        Params:
            i, j - (i, j) index in arr
            n, m - dimensions of sub-section to compute
        
        Returns:
            sub_section array
        """
        min_row, min_col, max_row, max_col = img_helpers.top_left_bot_right(i, j, n, m)
        # check sub-section is in range of the base arr
        if (max_row + 1 > self.terr_arr.shape[0] 
            or max_col + 1 > self.terr_arr.shape[1] 
            or min_row < 0 
            or min_col < 0):
            print("Sub-section out of range")
            return None
        
        return self.terr_arr[min_row:max_row, min_col:max_col]

    def add_to_xml(self):
        raise NotImplementedError 
    
"""
Sub-class of Terrain to represent an hfield in mujoco 
"""
class Hfield(Terrain):
    def __init__(self, terr_arr, path, name, position=(0, 0, 0), size=(100, 100, 0.01, 0.01)):
        """
        Added params:
            position - x,y,z position the hfield is centred at in mujoco
            size - x_rad, y_rad, elevation, base_z:

                    x_rad, y_rad - mujoco uses radius instead of length/width
                    elevation - data is normalised between 0-1, which is then scaled by this elevation value
                    base_z - depth of box in -z direction (serves as 'base')
        """
        super().__init__(terr_arr, path, name)
        self.size = size
        self.position = position

        self.size_str = f"{size[0]} {size[1]} {size[2]} {size[3]}"
        self.position_str = f"{position[0]} {position[1]} {position[2]}"

        # xml hfield element
        self.hfield_el = etree.Element("hfield", attrib={"name":self.name,
                                                    "file":self.img_path,
                                                    "size":self.size_str})
        # xml geom element (referencing hfield)
        self.geom_el = etree.Element("geom", attrib={"name":self.name,
                                                 "type":"hfield",
                                                 "pos":self.position_str,
                                                 "hfield":self.name})

    def rob_to_img_pos(self, pos):
        """
        Converts a position in mujoco to an (i, j) index in the terrain image

        NOTE: Assumes hfield is centred at pos == (0, 0, 0) in mujoco

        Params:
            pos - mujoco position
        """
        x_rad, y_rad = self.size[0], self.size[1]
        # +x == +i (right in mujoco and right in image respectively)
        i = int((pos[0] + x_rad) * ((self.image_dim[0] // 2) // x_rad))
        # +y == -j (up-screen in mujoco and down-screen in image respectively)
        j = int((-1 * pos[1] + y_rad) * ((self.image_dim[1] // 2) // x_rad))
        return (i, j)

    def add_to_xml(self, hfield_parent, geom_parent):
        """
        Adds both the hfield and its corresponding geom to the terrain file
        """
        hfield_parent.append(self.hfield_el)
        geom_parent.append(self.geom_el)
    

"""
Class to represent a mesh in mujoco
"""
class Mesh(Terrain):
    pass


"""
A class to generate terrain arrays for Terrain objects (see above)

NOTE: Terrain objects DO NOT require their terrain arrays to be generated this way. One can load their own 
if they wish, this just provides some already-configured ones.
"""
class TerrainGen():
    def gen_rand_ground_truth(self, zl, zh, dimensions):
        """
        Randomly generates a 2D numpy array that serves as the basis for the height map.
        NOTE: zl and zh define the range we sample from 
        """
        if len(dimensions) != 2:
            print("Dimensions of ground truth must be of form: (x, y) (or any numpy equivalent)")
            return None
        gt = np.random.uniform(low=zl, high=zh, size=dimensions)
        return gt

    def gen_curve(self, xl, xh, yl, yh, num_points, fn, plot=False):
        """
        fn is applied element-wise to generate a 2D numpy array that can serve as the basis of a surface in mujoco.
        NOTE: xl, xh, yl, yh define the x and y ranges (dimensions of the array)
        """
        x = np.linspace(xl, xh, num_points)
        y = np.linspace(yl, yh, num_points)
        x, y = np.meshgrid(x, y)
        fn = np.vectorize(fn)
        z = fn(x, y)
        # TODO : add plotting option
        return z

    ###################### TERRAIN FUNCTIONS ######################
    
    def saddle_func(self, x, y):
        return np.square(x) - np.square(y)

    def hump_func(self, x, y):
        z = 5*(np.square(x) + np.square(y))
        return z
    
    def gaussian(self, x, y, sigma=1):
        z = 25*(1/(2*np.pi*sigma**2)) * np.exp(-1*((0.1*x**2 + 0.1*y**2)/(2*sigma**2)))
        return z