# Nominal values for a bounding box to include only self-strikes when sitting on a flat surface.
SELF_STRIKE_SPHERICAL_IMAGE_GENERATION_SELF_FILTER:
 type: BOX
 parameters:
  dimensions: [2.0,2.0,0.9]
  shouldKeepPointsInside: true
