# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [0.00240066,0.00393687,0.0249253, 0.999998,0.00183422,4.868e-05,0.0010444]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0.00641464,-0.00051127,0.108514, 0.647522,0.273332,0.274849,0.656097]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.00286693
VELODYNE_LASER_TIME_OFFSET: 0.0028463
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [1,0,0]
