# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [-0.00457032,0.00189536,0.0292481, 0.999995,0.00065896,-0.00250862,0.00196246]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0.0162989,0.00425841,0.112958, 0.651949,0.27247,0.274207,0.652329]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.00640387
VELODYNE_LASER_TIME_OFFSET: 0.00619256
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [1,0,0]
