# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [-0.0114019,0.00618578,0.0294364, 0.989838,0.0028353,0.000901729,-0.142166]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0.0185736,0.00974628,0.11939, 0.551061,0.231801,0.307322,0.740374]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.00438922
VELODYNE_LASER_TIME_OFFSET: 0.00411928
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [1,0,0]
