# Dynamic calibration results
IMU_IMU_ANGULAR_VELOCITY_TIME_OFFSET: 0.0
IMU_IMU_LINEAR_ACCELERATION_TIME_OFFSET: 0.0
ENCODER_FIXED_STATIC_TRANSFORM_POSE_OFFSET: [-0.0108073,0.00251197,0.0339429, 0.999895,0.00309496,-0.000184899,0.0141588]
VELODYNE_STATIC_TRANSFORM_POSE_OFFSET: [0.0284647,0.00478923,0.116194, 0.662874,0.27365,0.270087,0.642469]
IMU_STATIC_TRANSFORM_POSE_OFFSET: [0,0,0, 1,0,0,0]
ENCODER_ROTATING_DYNAMIC_TRANSFORM_TIME_OFFSET: 0.0042523
VELODYNE_LASER_TIME_OFFSET: 0.0040348
# Static calibration results
ENCODER_CALIBRATION_VALUES: {}
LASER_CALIBRATION_VALUES: {}
# Forward axis
INIT_FORWARD_AXIS: [1,0,0]
