#!/usr/bin/env python

# Copyright (c) 2019
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230
#
# Author: Edwin Davis <edwin.davis@csiro.au>

import re

g_to_kg = 1.0 / 1.0e3
mm_to_m = 1.0 / 1.0e3
gmm2_to_kgm2 = 1.0 / 1.0e9

output_file_name = 'sw_inertia_tensors.xacro'

components = [('body',      'sw_files/Titan_Body.txt')]

header = ('<?xml version="1.0"?>\r\n'
          '<!-- This document was autogenerated by extract_solidworks.py -->\r\n'
          '<!-- EDITING THIS FILE BY HAND IS NOT RECOMMENDED -->\r\n'
          '<!-- data61, CSIRO (AU) -->\r\n'
          '\r\n'
          '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">\r\n'
          '\r\n')

footer = ('</robot>')

def make_inertial(component, file_name):
    properties = {}
    properties['name'] = component

    try:
        with open(file_name, 'r') as file_:
            data = file_.read()
    except:
        print("Problem reading {}. Does file exist?".format(file_name))

    try:
        template = r"Mass .*= (.*) grams"
        result = re.search(template, data).groups()
        properties['mass'] = float(result[0]) * g_to_kg
    except:
        print('No valid mass found in {}'.format(file_name))
        exit(1)

    try:
        template = (r'Center of mass: \( millimeters \)\s*'
                    r'X = ([^\n\r]*)\s*'
                    r'Y = ([^\n\r]*)\s*'
                    r'Z = ([^\n\r]*)\s*')
        result = re.search(template, data).groups()
        properties['X'] = float(result[0]) * mm_to_m
        properties['Y'] = float(result[1]) * mm_to_m
        properties['Z'] = float(result[2]) * mm_to_m
    except:
        print('No valid center of mass found')
        exit(1)

    try:
        template = (r'Moments of inertia: \( grams \*  square millimeters \)\s*'
                    r'Taken at the center of mass and aligned with the output coordinate system\.\s*'
                    r'Lxx = (.*)\tLxy = (.*)\tLxz = (.*)\s*'
                    r'Lyx = (.*)\tLyy = (.*)\tLyz = (.*)\s*'
                    r'Lzx = (.*)\tLzy = (.*)\tLzz = (.*)\s*')
        result = re.search(template, data).groups()
        properties['Ixx'] = float(result[0]) * gmm2_to_kgm2
        properties['Ixy'] = float(result[1]) * gmm2_to_kgm2
        properties['Ixz'] = float(result[2]) * gmm2_to_kgm2
        properties['Iyy'] = float(result[4]) * gmm2_to_kgm2
        properties['Iyz'] = float(result[5]) * gmm2_to_kgm2
        properties['Izz'] = float(result[8]) * gmm2_to_kgm2
    except:
        print('No valid inertia tensor found')
        exit(1)

    template = ('	<xacro:macro name="{name}_inertial">\r\n'
                '		<inertial>\r\n'
                '			<origin \r\n'
                '				xyz="{X} {Y} {Z}"\r\n'
                '				rpy="0 0 0" />\r\n'
                '			<mass value="{mass}" />\r\n'
                '			<inertia \r\n'
                '				ixx="{Ixx}"\r\n'
                '				ixy="{Ixy}"\r\n'
                '				ixz="{Ixz}"\r\n'
                '				iyy="{Iyy}"\r\n'
                '				iyz="{Iyz}"\r\n'
                '				izz="{Izz}" />\r\n'
                '		</inertial>\r\n'
                '	</xacro:macro>\r\n'
                '\r\n')

    inertial = template.format(**properties)

    return inertial


if __name__ == '__main__':
    output_data = header
    for component, file_name in components:
        inertial = make_inertial(component, file_name)
        output_data += inertial
    output_data += footer

    with open(output_file_name, 'w') as file_:
        file_.write(output_data)

    print output_data